debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.bumsu.bulletin_with_crud: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: bumsu
    password: 864862
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  h2:
    console:
  sql.init.mode: always
  data:
    rest:
      base-path: /api
      detection-strategy: annotated